api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        
        pagination:
            client_items_per_page: true
            client_enabled: true
            enabled_parameter_name: 'page'
            enabled: false
            
