version: '3'

services:
  php:
    build: ./docker/apache/
    depends_on:
      - db
    volumes:
      - ./docker/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/etc/php/php-cli.ini:/usr/local/etc/php/php-cli.ini:ro
      - ./app/symfony:/var/www/symfony:cached
      - /var/www/symfony/var/cache/
      - ./app/symfony/vendor:/var/www/symfony/vendor
    environment:
      DATABASE_URL: mysql://root:azerty@db:3306/app
    ports:
      - "8000:80"

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    restart: always
    volumes:
      - ./app/front:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./docker/bdd/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - db-data:/var/lib/mysql/:delegated
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: azerty


  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8001:80"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"

volumes:
  #  app-vendor:
  db-data:
