events {

}

http {
  server {
  server_name whoami.mydomain.com
    listen 80;
    listen 443 ssl;
    ssl_certificate     /etc/nginx/certificates/cert.pem;
    ssl_certificate_key /etc/nginx/certificates/key.pem;


  }
}
