map $http_x_forwarded_proto $fe_https {
  default off;
  https on;
}

server {
    listen 80;

    listen 443 ssl;
    ssl_certificate     /etc/nginx/certificates/cert.pem;
    ssl_certificate_key /etc/nginx/certificates/key.pem;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
      proxy_pass http://whoami:80;
    }
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
}
