vich_uploader:
    db_driver: orm

    mappings:
        products_object:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/asset/images/products'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        code_object:
            uri_prefix: /images/orders
            upload_destination: '%kernel.project_dir%/public/asset/images/orders'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

